# -*- coding: utf-8 -*-
"""online_retail_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeuW8W04v88aOMLZoWmkSjBlhw2127JE
"""

# Online Retail Data Analysis

## Data Analyst Assessment

**Objective:** Analyze online retail transaction data to identify sales trends, customer behavior, product performance, and business opportunities.

**Tools Used:**
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Google Colab

from google.colab import drive

drive.mount('/content/drive')

import os

os.listdir('/content/drive/MyDrive/')

file_path = '/content/drive/MyDrive/online_retail_II.xlsx'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

df_2009_2010 = pd.read_excel(
    file_path,
    sheet_name='Year 2009-2010'
)

print(df_2009_2010.shape)

df_2010_2011 = pd.read_excel(
    file_path,
    sheet_name='Year 2010-2011'
)

print(df_2010_2011.shape)

df = pd.concat(
    [df_2009_2010, df_2010_2011],
    ignore_index=True
)

print("Combined dataset shape:", df.shape)

df.head()

df.info()

df.columns.tolist()

missing = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum() / len(df) * 100).round(2)
})

missing

print("Duplicate rows:", df.duplicated().sum())

print("Negative quantities:", (df['Quantity'] < 0).sum())
print("Zero quantities:", (df['Quantity'] == 0).sum())
print("Zero/negative prices:", (df['Price'] <= 0).sum())

print("Duplicate rows:", df.duplicated().sum())
print("Negative quantities:", (df['Quantity'] < 0).sum())
print("Zero quantities:", (df['Quantity'] == 0).sum())
print("Zero/negative prices:", (df['Price'] <= 0).sum())

df[df['Quantity'] < 0].head(10)

df[df['Price'] <= 0].head(10)

duplicate_rows = df[df.duplicated(keep=False)]

print("Total duplicate records:", len(duplicate_rows))

duplicate_rows.head(20)

df[df.duplicated()].head(10)

df[df.duplicated()].head(10)

# Check the number of rows and columns
print("Rows and Columns:", df.shape)

# Check column names
print("\nColumn Names:")
print(df.columns)

# Check data types and missing values
print("\nDataset Information:")
df.info()

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate Rows:", df.duplicated().sum())

# Basic statistical summary
df.describe(include='all')

# Check missing values
print("Missing values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:")
print(df.duplicated().sum())

# Check negative quantities
print("\nNegative quantity rows:")
print((df['Quantity'] < 0).sum())

# Check zero/negative prices
print("\nZero price rows:")
print((df['Price'] == 0).sum())

print("\nNegative price rows:")
print((df['Price'] < 0).sum())

# Check invoices that start with C
print("\nCancelled invoices:")
print(df['Invoice'].astype(str).str.startswith('C').sum())

# Create a temporary sales amount column
df['Sales'] = df['Quantity'] * df['Price']

print("Sales summary:")
print(df['Sales'].describe())

# Top 10 products by quantity sold
print("\nTop 10 products by quantity:")
print(
    df.groupby('Description')['Quantity']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

# Check missing values
print("Missing values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate rows:")
print(df.duplicated().sum())

# Check negative quantities
print("\nNegative quantity rows:")
print((df['Quantity'] < 0).sum())

# Check zero prices
print("\nZero price rows:")
print((df['Price'] == 0).sum())

# Check negative prices
print("\nNegative price rows:")
print((df['Price'] < 0).sum())

# Check cancelled invoices
print("\nCancelled invoices:")
print(df['Invoice'].astype(str).str.startswith('C').sum())

# ==============================
# DATA CLEANING & PROCESSING
# ==============================

# Make a copy of the original dataset
clean_df = df.copy()

# 1. Convert InvoiceDate to datetime
clean_df['InvoiceDate'] = pd.to_datetime(clean_df['InvoiceDate'])

# 2. Remove exact duplicate rows
clean_df = clean_df.drop_duplicates()

# 3. Remove rows where Description is missing
clean_df = clean_df.dropna(subset=['Description'])

# 4. Remove invalid prices (zero or negative)
clean_df = clean_df[clean_df['Price'] > 0]

# 5. Create Sales / Revenue column
clean_df['Sales'] = clean_df['Quantity'] * clean_df['Price']

# 6. Create useful date fields
clean_df['Year'] = clean_df['InvoiceDate'].dt.year
clean_df['Month'] = clean_df['InvoiceDate'].dt.month
clean_df['Month_Name'] = clean_df['InvoiceDate'].dt.strftime('%b')
clean_df['Year_Month'] = clean_df['InvoiceDate'].dt.to_period('M').astype(str)

# 7. Create Return flag
clean_df['Is_Return'] = clean_df['Quantity'] < 0

# 8. Create Invoice Cancellation flag
clean_df['Is_Cancelled'] = (
    clean_df['Invoice'].astype(str).str.startswith('C')
)

# 9. Create weekday
clean_df['Day_of_Week'] = clean_df['InvoiceDate'].dt.day_name()

# 10. Create customer-level identifier
clean_df['Has_Customer_ID'] = clean_df['Customer ID'].notna()

# Display final information
print("Original rows:", len(df))
print("Final rows:", len(clean_df))
print("Rows removed:", len(df) - len(clean_df))

print("\nFinal columns:")
print(clean_df.columns.tolist())

print("\nRemaining missing values:")
print(clean_df.isnull().sum())

print("\nFinal dataset shape:")
print(clean_df.shape)

# ==============================
# BUSINESS ANALYSIS TABLES
# ==============================

# Monthly sales
monthly_sales = (
    clean_df.groupby('Year_Month')['Sales']
    .sum()
    .reset_index()
)

# Country-wise sales
country_sales = (
    clean_df.groupby('Country')['Sales']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

# Product-wise sales
product_sales = (
    clean_df.groupby('Description')['Sales']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

# Product quantity
product_quantity = (
    clean_df.groupby('Description')['Quantity']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

# Customer sales
customer_sales = (
    clean_df.dropna(subset=['Customer ID'])
    .groupby('Customer ID')['Sales']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

# Invoice/order summary
order_summary = clean_df.groupby('Invoice').agg(
    Order_Value=('Sales', 'sum'),
    Items=('Quantity', 'sum'),
    Customer_ID=('Customer ID', 'first'),
    Country=('Country', 'first')
).reset_index()

print("Monthly Sales:")
print(monthly_sales.head())

print("\nTop 10 Countries:")
print(country_sales.head(10))

print("\nTop 10 Products by Sales:")
print(product_sales.head(10))

print("\nTop 10 Customers:")
print(customer_sales.head(10))

# ==============================
# KEY BUSINESS KPIs
# ==============================

total_sales = clean_df['Sales'].sum()
total_orders = clean_df['Invoice'].nunique()
total_customers = clean_df['Customer ID'].nunique()
total_products = clean_df['StockCode'].nunique()

average_order_value = total_sales / total_orders

return_transactions = (clean_df['Quantity'] < 0).sum()

return_rate = (return_transactions / len(clean_df)) * 100

print("Total Sales:", round(total_sales, 2))
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Total Products:", total_products)
print("Average Order Value:", round(average_order_value, 2))
print("Return Transaction Rate:", round(return_rate, 2), "%")

# Key Business KPIs

The cleaned dataset was used to calculate the following key performance
indicators:

- Total Sales: 19,014,209.84
- Total Orders: 48,369
- Total Customers: 5,939
- Total Products: 4,932
- Average Order Value: 393.11
- Return Transaction Rate: 1.86%

These KPIs provide a high-level overview of the retailer's sales performance,
customer base, product range, order value, and return activity.